
esphome:
  name: esp32_c3_super_mini
  friendly_name: ESP32_C3_SuperMini
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32c3
    board_build.f_cpu: 80000000L

  project:
    name: MorganMLGman.ESPHome_Templates
    version: "1.1.1"

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf

logger:
  hardware_uart: UART0 # USB_SERIAL_JTAG
  level: DEBUG

api:
  reboot_timeout: 10min

ota:
  - platform: esphome

dashboard_import:
  package_import_url: github://MorganMLGman/ESPHome_Templates/ESP32_C3_SuperMini.yaml@master

wifi:
  reboot_timeout: 10min

  ap:

captive_portal:

esp32_improv:
  authorizer: none

improv_serial:

time:
  - platform: homeassistant
    id: homeassistant_time

text_sensor:
  - platform: version
    name: ESPHome Version
    entity_category: "diagnostic"

  - platform: wifi_info
    ip_address:
      name: IP Address
      entity_category: "diagnostic"
    ssid:
      name: WiFi SSID
      entity_category: "diagnostic"
    bssid:
      name: WiFi BSSID
      entity_category: "diagnostic"

binary_sensor:
  - platform: status
    name: Status
    device_class: connectivity

sensor:
  - platform: wifi_signal
    name: WiFi Signal dB
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy
    source_id: wifi_signal_db
    name: WiFi Signal Percent
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"

  - platform: uptime
    name: Uptime
    update_interval: 60s
    accuracy_decimals: 0
    icon: mdi:clock-outline
    entity_category: "diagnostic"

  - platform: internal_temperature
    name: "Internal Temperature"

button:
  - platform: shutdown
    name: Shut Down

  - platform: restart
    name: Restart
  
  - platform: safe_mode
    name: Safe Mode

# light:
#   - platform: status_led
#     name: "User LED"
#     pin: 
#       number: GPIO8
#       inverted: True
