packages:
  device_base: !include common/base_wifi.yaml

esphome:
  name: esp32_st7789v
  friendly_name: ESP32_ST7789V
  name_add_mac_suffix: True

  project:
    name: MorganMLGman.ESPHome_Templates
    version: "1.2.0"

esp32:
  board: esp32dev
  flash_size: 16MB
  framework:
    type: esp-idf
    version: recommended


update:
  - platform: http_request
    id: update_http_request
    update_interval: 1h
    name: ESP32_ST7789V Firmware
    source: https://morganmlgman.github.io/ESPHome_Templates/firmware/ESPHome_Templates.manifest.json
    disabled_by_default: false

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19
  # miso_pin: GPIO

