packages:
  device_base: !include common/base_wifi.yaml

esphome:
  name: esp32_st7789v
  friendly_name: ESP32_ST7789V
  name_add_mac_suffix: True

  project:
    name: MorganMLGman.ESPHome_Templates
    version: "1.1.7"

esp32:
  board: esp32dev
  flash_size: 16MB
  framework:
    type: esp-idf
    version: recommended


update:
  - platform: http_request
    id: update_http_request
    update_interval: 1h
    name: ESP32_ST7789V Firmware
    source: https://morganmlgman.github.io/ESPHome_Templates/firmware/ESPHome_Templates.manifest.json
    disabled_by_default: false

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19
  # miso_pin: GPIO

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: True
    name: "Button 1"
    id: button_1

  - platform: gpio
    pin:
      number: GPIO35
      inverted: True
    name: "Button 2"
    id: button_2

font:
  - file: "gfonts://Roboto"
    id: roboto20
    size: 20

output:
  - platform: ledc
    pin: GPIO4
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON
