packages:
  device_base: !include common/base_eth.yaml

esphome:
  name: wt32_eth1
  friendly_name: WT32_ETH1
  name_add_mac_suffix: True
  platformio_options:
    board_build.flash_mode: dio

  project:
    name: MorganMLGman.ESPHome_Templates
    version: "1.2.0"

esp32:
  board: wt32-eth01
  framework:
    type: esp-idf

update:
  - platform: http_request
    id: update_http_request
    name: WT32_ETH1 Firmware
    source: https://morganmlgman.github.io/ESPHome_Templates/firmware/ESPHome_Templates.manifest.json
    disabled_by_default: false
