packages:
  core: !include WT32_ETH1.yaml

esphome:
  project:
    name: MorganMLGman.ESPHome_Templates
    version: dev # This will be replaced by the github workflows with the `release` version

# This should point to the public location of the yaml file that will be adopted.
# In this case it is the core yaml file that does not contain the extra things
# that are provided by this factory yaml file as the user does not need these once adopted.
dashboard_import:
  package_import_url: github://MorganMLGman/ESPHome_Templates/WT32_ETH1.yaml@main
