logger:
  level: DEBUG

api:
  reboot_timeout: 10min

ota:
  - platform: esphome
    id: ota_esphome
  - platform: http_request
    id: ota_http_request

http_request:

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

time:
  - platform: homeassistant
    id: homeassistant_time

text_sensor:
  - platform: ethernet_info
    ip_address:      
      entity_category: "diagnostic"
      name: IP Address
    dns_address:
      entity_category: "diagnostic"
      name: DNS Address
    mac_address:
      entity_category: "diagnostic"
      name: MAC Address

  - platform: version
    name: ESPHome Version

binary_sensor:
  - platform: status
    name: Status
    device_class: connectivity

sensor:
  - platform: uptime
    name: Uptime
    entity_category: "diagnostic"
    update_interval: 60s
    accuracy_decimals: 0

  - platform: internal_temperature
    entity_category: "diagnostic"
    name: "Internal Temperature"

button:
  - platform: shutdown
    name: Shut Down

  - platform: restart
    name: Restart
  
  - platform: safe_mode
    name: Safe Mode