name: CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  ci:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - ESP32_C3_SuperMini.yaml
          - ESP32_S3_SuperMini_RGB
          - ESP8266_NodeMCU.yaml
          - WT32_ETH1.yaml

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.7
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v4.0.1
        with:
          yaml-file: ${{ matrix.file }}
