name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      # CHANGEME: Set the filenames of your config files here:
      files:
        ESP32_C3_SuperMini.yaml,
        ESP32_S3_SuperMini_RGB.yaml,
        ESP8266_NodeMCU.yaml,
        WT32_ETH1.yaml

      # CHANGEME: Set the name of your project here:
      name: ESPHome_Templates
